version: '3.8'

services:
  postgres:
    build:
      context: ./
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
      
  nats-streaming:
    restart: always
    image: nats-streaming:0.25.5-alpine3.18
    ports:
      - 4222:4222
    command:
    - "--cluster_id"
    - "testcluster"

  main:
    depends_on:
      - postgres
      - nats-streaming
    build:
      context: ./
      dockerfile: app.Dockerfile
    restart: always
    container_name: main
    ports:
      - "9090:9090"
    environment:
      - HTTP_ADDR=${PORT}
      - NT_URL=${NATS_URL}
      - PG_URL=${POSTGRES_URL}
      - PG_HOST=${POSTGRES_HOST}
      - PG_PORT=${POSTGRES_PORT}
      
volumes:
  db_data: